name: Readme Translate
author: Ephraim Atta-Duncan
description: Translate the Readme to another language

inputs:
  LANG:
    description: 'The Language you want to translate to'
    required: true
    default: ['ru']

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: book-open
  color: black
